//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Web.TestOTPWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestOTPWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name StrUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Password", ReplyAction="*")]
        Teckraft.Web.TestOTPWebService.PasswordResponse Password(Teckraft.Web.TestOTPWebService.PasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Password", ReplyAction="*")]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.PasswordResponse> PasswordAsync(Teckraft.Web.TestOTPWebService.PasswordRequest request);
        
        // CODEGEN: Generating message contract since element name StrUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Teckraft.Web.TestOTPWebService.LoginResponse Login(Teckraft.Web.TestOTPWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginResponse> LoginAsync(Teckraft.Web.TestOTPWebService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name StrUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginValidity", ReplyAction="*")]
        Teckraft.Web.TestOTPWebService.LoginValidityResponse LoginValidity(Teckraft.Web.TestOTPWebService.LoginValidityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginValidity", ReplyAction="*")]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginValidityResponse> LoginValidityAsync(Teckraft.Web.TestOTPWebService.LoginValidityRequest request);
        
        // CODEGEN: Generating message contract since element name StrUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgetPassword", ReplyAction="*")]
        Teckraft.Web.TestOTPWebService.ForgetPasswordResponse ForgetPassword(Teckraft.Web.TestOTPWebService.ForgetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.ForgetPasswordResponse> ForgetPasswordAsync(Teckraft.Web.TestOTPWebService.ForgetPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Password", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.PasswordRequestBody Body;
        
        public PasswordRequest() {
        }
        
        public PasswordRequest(Teckraft.Web.TestOTPWebService.PasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrMobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrApplName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrApplCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StrEmailId;
        
        public PasswordRequestBody() {
        }
        
        public PasswordRequestBody(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            this.StrUsername = StrUsername;
            this.StrMobileNo = StrMobileNo;
            this.StrApplName = StrApplName;
            this.StrApplCode = StrApplCode;
            this.StrEmailId = StrEmailId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.PasswordResponseBody Body;
        
        public PasswordResponse() {
        }
        
        public PasswordResponse(Teckraft.Web.TestOTPWebService.PasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PasswordResult;
        
        public PasswordResponseBody() {
        }
        
        public PasswordResponseBody(bool PasswordResult) {
            this.PasswordResult = PasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Teckraft.Web.TestOTPWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrApplName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrApplCode;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            this.StrUsername = StrUsername;
            this.StrPassword = StrPassword;
            this.StrApplName = StrApplName;
            this.StrApplCode = StrApplCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Teckraft.Web.TestOTPWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginValidityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginValidity", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.LoginValidityRequestBody Body;
        
        public LoginValidityRequest() {
        }
        
        public LoginValidityRequest(Teckraft.Web.TestOTPWebService.LoginValidityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginValidityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrApplName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrApplCode;
        
        public LoginValidityRequestBody() {
        }
        
        public LoginValidityRequestBody(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            this.StrUsername = StrUsername;
            this.StrPassword = StrPassword;
            this.StrApplName = StrApplName;
            this.StrApplCode = StrApplCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginValidityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginValidityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.LoginValidityResponseBody Body;
        
        public LoginValidityResponse() {
        }
        
        public LoginValidityResponse(Teckraft.Web.TestOTPWebService.LoginValidityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginValidityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginValidityResult;
        
        public LoginValidityResponseBody() {
        }
        
        public LoginValidityResponseBody(bool LoginValidityResult) {
            this.LoginValidityResult = LoginValidityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgetPassword", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.ForgetPasswordRequestBody Body;
        
        public ForgetPasswordRequest() {
        }
        
        public ForgetPasswordRequest(Teckraft.Web.TestOTPWebService.ForgetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForgetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrMobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrApplName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrApplCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StrEmailId;
        
        public ForgetPasswordRequestBody() {
        }
        
        public ForgetPasswordRequestBody(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            this.StrUsername = StrUsername;
            this.StrMobileNo = StrMobileNo;
            this.StrApplName = StrApplName;
            this.StrApplCode = StrApplCode;
            this.StrEmailId = StrEmailId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForgetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForgetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teckraft.Web.TestOTPWebService.ForgetPasswordResponseBody Body;
        
        public ForgetPasswordResponse() {
        }
        
        public ForgetPasswordResponse(Teckraft.Web.TestOTPWebService.ForgetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForgetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ForgetPasswordResult;
        
        public ForgetPasswordResponseBody() {
        }
        
        public ForgetPasswordResponseBody(bool ForgetPasswordResult) {
            this.ForgetPasswordResult = ForgetPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Teckraft.Web.TestOTPWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Teckraft.Web.TestOTPWebService.WebServiceSoap>, Teckraft.Web.TestOTPWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teckraft.Web.TestOTPWebService.PasswordResponse Teckraft.Web.TestOTPWebService.WebServiceSoap.Password(Teckraft.Web.TestOTPWebService.PasswordRequest request) {
            return base.Channel.Password(request);
        }
        
        public bool Password(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            Teckraft.Web.TestOTPWebService.PasswordRequest inValue = new Teckraft.Web.TestOTPWebService.PasswordRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.PasswordRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrMobileNo = StrMobileNo;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            inValue.Body.StrEmailId = StrEmailId;
            Teckraft.Web.TestOTPWebService.PasswordResponse retVal = ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).Password(inValue);
            return retVal.Body.PasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.PasswordResponse> Teckraft.Web.TestOTPWebService.WebServiceSoap.PasswordAsync(Teckraft.Web.TestOTPWebService.PasswordRequest request) {
            return base.Channel.PasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.PasswordResponse> PasswordAsync(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            Teckraft.Web.TestOTPWebService.PasswordRequest inValue = new Teckraft.Web.TestOTPWebService.PasswordRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.PasswordRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrMobileNo = StrMobileNo;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            inValue.Body.StrEmailId = StrEmailId;
            return ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).PasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teckraft.Web.TestOTPWebService.LoginResponse Teckraft.Web.TestOTPWebService.WebServiceSoap.Login(Teckraft.Web.TestOTPWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            Teckraft.Web.TestOTPWebService.LoginRequest inValue = new Teckraft.Web.TestOTPWebService.LoginRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.LoginRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrPassword = StrPassword;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            Teckraft.Web.TestOTPWebService.LoginResponse retVal = ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginResponse> Teckraft.Web.TestOTPWebService.WebServiceSoap.LoginAsync(Teckraft.Web.TestOTPWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginResponse> LoginAsync(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            Teckraft.Web.TestOTPWebService.LoginRequest inValue = new Teckraft.Web.TestOTPWebService.LoginRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.LoginRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrPassword = StrPassword;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            return ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teckraft.Web.TestOTPWebService.LoginValidityResponse Teckraft.Web.TestOTPWebService.WebServiceSoap.LoginValidity(Teckraft.Web.TestOTPWebService.LoginValidityRequest request) {
            return base.Channel.LoginValidity(request);
        }
        
        public bool LoginValidity(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            Teckraft.Web.TestOTPWebService.LoginValidityRequest inValue = new Teckraft.Web.TestOTPWebService.LoginValidityRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.LoginValidityRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrPassword = StrPassword;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            Teckraft.Web.TestOTPWebService.LoginValidityResponse retVal = ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).LoginValidity(inValue);
            return retVal.Body.LoginValidityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginValidityResponse> Teckraft.Web.TestOTPWebService.WebServiceSoap.LoginValidityAsync(Teckraft.Web.TestOTPWebService.LoginValidityRequest request) {
            return base.Channel.LoginValidityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.LoginValidityResponse> LoginValidityAsync(string StrUsername, string StrPassword, string StrApplName, string StrApplCode) {
            Teckraft.Web.TestOTPWebService.LoginValidityRequest inValue = new Teckraft.Web.TestOTPWebService.LoginValidityRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.LoginValidityRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrPassword = StrPassword;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            return ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).LoginValidityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teckraft.Web.TestOTPWebService.ForgetPasswordResponse Teckraft.Web.TestOTPWebService.WebServiceSoap.ForgetPassword(Teckraft.Web.TestOTPWebService.ForgetPasswordRequest request) {
            return base.Channel.ForgetPassword(request);
        }
        
        public bool ForgetPassword(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            Teckraft.Web.TestOTPWebService.ForgetPasswordRequest inValue = new Teckraft.Web.TestOTPWebService.ForgetPasswordRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.ForgetPasswordRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrMobileNo = StrMobileNo;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            inValue.Body.StrEmailId = StrEmailId;
            Teckraft.Web.TestOTPWebService.ForgetPasswordResponse retVal = ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).ForgetPassword(inValue);
            return retVal.Body.ForgetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.ForgetPasswordResponse> Teckraft.Web.TestOTPWebService.WebServiceSoap.ForgetPasswordAsync(Teckraft.Web.TestOTPWebService.ForgetPasswordRequest request) {
            return base.Channel.ForgetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teckraft.Web.TestOTPWebService.ForgetPasswordResponse> ForgetPasswordAsync(string StrUsername, string StrMobileNo, string StrApplName, string StrApplCode, string StrEmailId) {
            Teckraft.Web.TestOTPWebService.ForgetPasswordRequest inValue = new Teckraft.Web.TestOTPWebService.ForgetPasswordRequest();
            inValue.Body = new Teckraft.Web.TestOTPWebService.ForgetPasswordRequestBody();
            inValue.Body.StrUsername = StrUsername;
            inValue.Body.StrMobileNo = StrMobileNo;
            inValue.Body.StrApplName = StrApplName;
            inValue.Body.StrApplCode = StrApplCode;
            inValue.Body.StrEmailId = StrEmailId;
            return ((Teckraft.Web.TestOTPWebService.WebServiceSoap)(this)).ForgetPasswordAsync(inValue);
        }
    }
}
