//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Web.CRWorkflowInstanceServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRWorkflowInstanceServices.IWFInstanceService")]
    public interface IWFInstanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFInstanceService/Terminate", ReplyAction="http://tempuri.org/IWFInstanceService/TerminateResponse")]
        void Terminate(System.Guid InstanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFInstanceService/Terminate", ReplyAction="http://tempuri.org/IWFInstanceService/TerminateResponse")]
        System.Threading.Tasks.Task TerminateAsync(System.Guid InstanceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWFInstanceServiceChannel : Teckraft.Web.CRWorkflowInstanceServices.IWFInstanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFInstanceServiceClient : System.ServiceModel.ClientBase<Teckraft.Web.CRWorkflowInstanceServices.IWFInstanceService>, Teckraft.Web.CRWorkflowInstanceServices.IWFInstanceService {
        
        public WFInstanceServiceClient() {
        }
        
        public WFInstanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFInstanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFInstanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFInstanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Terminate(System.Guid InstanceId) {
            base.Channel.Terminate(InstanceId);
        }
        
        public System.Threading.Tasks.Task TerminateAsync(System.Guid InstanceId) {
            return base.Channel.TerminateAsync(InstanceId);
        }
    }
}
