//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Web.Models.OTP
{

    public partial class OTP
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime Time { get; set; }
        public string ApplnName { get; set; }
        public string ApplnCode { get; set; }
        public bool Flag { get; set; }
    }
}
