//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUserSession
    {
        public int UserId { get; set; }
        public string SessionId { get; set; }
        public System.DateTime RCT { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
