//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int ID { get; set; }
        public string EventType { get; set; }
        public string Details { get; set; }
        public System.DateTime RCT { get; set; }
        public int RCB { get; set; }
        public string ApplicationName { get; set; }
        public string IP { get; set; }
        public string Url { get; set; }
    }
}
