//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueManagementCommentLog
    {
        public int Id { get; set; }
        public string ID_Comments { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ID_Request { get; set; }
        public string id_System_Name { get; set; }
        public string ID_Status { get; set; }
        public string ID_Pending_With_Email { get; set; }
        public Nullable<System.DateTime> RCT { get; set; }
        public Nullable<int> RCB { get; set; }
        public Nullable<System.DateTime> RUT { get; set; }
        public Nullable<int> RUB { get; set; }
        public Nullable<bool> UploadFlag { get; set; }
        public Nullable<int> ID_Status_Id { get; set; }
        public string RCBEmail { get; set; }
        public string RCBEmpCode { get; set; }
        public string RCBEmpName { get; set; }
        public string RUBEmail { get; set; }
        public string RUBEmpCode { get; set; }
        public string RUBEmpName { get; set; }
        public Nullable<System.DateTime> Target_Date { get; set; }
    
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
