//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Data.Sql
{
    using System;
    
    public partial class spIssueDetails_Result1
    {
        public string chapternamefromsystem { get; set; }
        public string chapternamedisplay { get; set; }
        public string id_data_load_date { get; set; }
        public string chapterOwner { get; set; }
        public string id_request { get; set; }
        public string ID_Issue_Detail1 { get; set; }
        public string id_status { get; set; }
        public string id_reported_by_name { get; set; }
        public string id_reported_by_email { get; set; }
        public string id_dept { get; set; }
        public string id_location { get; set; }
        public string id_pending_with_name { get; set; }
        public string id_pending_with_email { get; set; }
        public string ID_Responsible_Name { get; set; }
        public string ID_Responsible_Email { get; set; }
        public string ID_Logged_Date { get; set; }
        public Nullable<int> pendingSince { get; set; }
        public string id_tat_status { get; set; }
        public string id_comments { get; set; }
        public string ID_Target_Date { get; set; }
        public string ID_Category { get; set; }
        public string AnchorSentBackComments { get; set; }
        public string AnchorCommentDate { get; set; }
        public string AnchorName { get; set; }
        public string pendingStatus { get; set; }
    }
}
