//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.IssueManagementCommentLogs = new HashSet<IssueManagementCommentLog>();
            this.IssueManagementCommentLogs1 = new HashSet<IssueManagementCommentLog>();
            this.IssueManagementAnchorComments = new HashSet<IssueManagementAnchorComment>();
            this.IssueManagementAnchorComments1 = new HashSet<IssueManagementAnchorComment>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Picture { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public Nullable<int> RA1 { get; set; }
        public Nullable<int> RA2 { get; set; }
        public string racd1 { get; set; }
        public string racd2 { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> IsITFH { get; set; }
        public Nullable<bool> IsITEvaluator { get; set; }
        public string orgemail { get; set; }
        public string Designation { get; set; }
        public Nullable<int> hod { get; set; }
        public Nullable<int> olduserid { get; set; }
        public Nullable<int> newuserid { get; set; }
        public string OverrideEmail { get; set; }
        public string OverrideMobile { get; set; }
        public Nullable<bool> IsSubITFH { get; set; }
    
        public virtual CurrentUserSession CurrentUserSession { get; set; }
        public virtual Division Division { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
        public virtual ICollection<IssueManagementCommentLog> IssueManagementCommentLogs { get; set; }
        public virtual ICollection<IssueManagementCommentLog> IssueManagementCommentLogs1 { get; set; }
        public virtual ICollection<IssueManagementAnchorComment> IssueManagementAnchorComments { get; set; }
        public virtual ICollection<IssueManagementAnchorComment> IssueManagementAnchorComments1 { get; set; }
    }
}
