//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teckraft.Web.CRCustomWorkflowServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRCustomWorkflowServices.ICRCustomWFService")]
    public interface ICRCustomWFService {

        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/Update", ReplyAction = "http://tempuri.org/ICRCustomWFService/UpdateResponse")]
       // Teckraft.Core.Domian.Settings.Requisition Update(Teckraft.Core.Domian.Settings.Requisition workItem);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/Update", ReplyAction = "http://tempuri.org/ICRCustomWFService/UpdateResponse")]
        //System.Threading.Tasks.Task<Teckraft.Core.Domian.Transactions.CR> UpdateAsync(Teckraft.Core.Domian.Transactions.CR workItem);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/UpdateTask", ReplyAction = "http://tempuri.org/ICRCustomWFService/UpdateTaskResponse")]
        //Teckraft.Core.Workflow.Task UpdateTask(Teckraft.Core.Workflow.Task workItem);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/UpdateTask", ReplyAction = "http://tempuri.org/ICRCustomWFService/UpdateTaskResponse")]
        //System.Threading.Tasks.Task<Teckraft.Core.Workflow.Task> UpdateTaskAsync(Teckraft.Core.Workflow.Task workItem);

      //  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/Create", ReplyAction = "http://tempuri.org/ICRCustomWFService/CreateResponse")]
       // Teckraft.Core.Domian.Settings.Requisition Create(Teckraft.Core.Domian.Settings.Requisition workItem);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICRCustomWFService/Create", ReplyAction = "http://tempuri.org/ICRCustomWFService/CreateResponse")]
        //System.Threading.Tasks.Task<Teckraft.Core.Domian.Transactions.CR> CreateAsync(Teckraft.Core.Domian.Transactions.CR workItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRCustomWFServiceChannel : Teckraft.Web.CRCustomWorkflowServices.ICRCustomWFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRCustomWFServiceClient : System.ServiceModel.ClientBase<Teckraft.Web.CRCustomWorkflowServices.ICRCustomWFService>, Teckraft.Web.CRCustomWorkflowServices.ICRCustomWFService {
        
        public CRCustomWFServiceClient() {
        }
        
        public CRCustomWFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRCustomWFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRCustomWFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRCustomWFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        //public Teckraft.Core.Domian.Settings.Requisition Update(Teckraft.Core.Domian.Settings.Requisition workItem)
        //{
        //    return base.Channel.Update(workItem);
        //}

        //public System.Threading.Tasks.Task<Teckraft.Core.Domian.Transactions.CR> UpdateAsync(Teckraft.Core.Domian.Transactions.CR workItem)
        //{
        //    return base.Channel.UpdateAsync(workItem);
        //}

        //public Teckraft.Core.Workflow.Task UpdateTask(Teckraft.Core.Workflow.Task workItem)
        //{
        //    return base.Channel.UpdateTask(workItem);
        //}

        //public System.Threading.Tasks.Task<Teckraft.Core.Workflow.Task> UpdateTaskAsync(Teckraft.Core.Workflow.Task workItem)
        //{
        //    return base.Channel.UpdateTaskAsync(workItem);
        //}

        //public Teckraft.Core.Domian.Settings.Requisition Create(Teckraft.Core.Domian.Settings.Requisition workItem)
        //{
        //    return base.Channel.Create(workItem);
        //}

        //public System.Threading.Tasks.Task<Teckraft.Core.Domian.Transactions.CR> CreateAsync(Teckraft.Core.Domian.Transactions.CR workItem)
        //{
        //    return base.Channel.CreateAsync(workItem);
        //}
    }
}
